openapi: 3.0.0
info: 
  title: Стажировка
  version: 1.0.0
servers:
  - url: http:/127.0.0.1:8000/api/documentation
paths:
  
  /api/users/{limit}/{offset}:
    get: 
      summary: Получение пользователей
      operationId: GetAllUsers
      parameters:
        - name: limit
          in: path
          required: true
          description: Количество пользователей
          schema:
            type: integer
            
        - name: offset
          in: path
          required: true
          description: Игнорирование пользователей
          schema:
            type: integer
            
      tags: 
        - Users
      responses:
        '200':
          description: Успешный вывод всех пользователей
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
                
  /api/users/{id}:
    get: 
      summary: Получение пользователя по id
      tags:
        - Users
      operationId: GetUserById
      parameters:
        - name: id
          in: path
          required: true
          description: id пользователя
          schema:
            type: integer
          
      responses:
        '200':
          description: Пользователь найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
                
        '204':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  
    delete:
      summary: Удаление пользователя по id
      tags:
        - Users
      operationId: DeleteUserById
      parameters:
        - name: id
          in: path
          required: true
          description: id пользователя
          schema:
            type: integer
            
      responses:
        '200':
          description: Пользователь удален
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
                  
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  
  /api/users:
    patch:
      summary: Обновление имени и\или аватара пользователя
      tags:
        - Users
      operationId: UpdateUserAvatarAndNameById
      
      responses:
        '200':
          description: Имя и\или аватар изменен
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
                  
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorize"
        '422':
          description: Некорректные данные 
  
  /api/auth/register:
    post: 
      summary: Регистрация пользователя
      tags:
        - Auth
      operationId: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
              
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        
        '422':
          description: Некорректный email/password или пользователь с таким email существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntity"
  
  /api/auth/login:
    post: 
      summary: Авторизация пользователя
      tags:
        - Auth
      operationId: LoginUser
      responses:
        '201':
          description: Пользователь успешно авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessLogin"
        
        '422':
          description: Некорректный email/password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntity"
  
  /api/password/forgot:
    post:
      summary: Восстановление пароля пользователя
      tags:
        - Password
      operationId: ForgotPassword
      responses:
        '200':
          description: Ссылка для сброса пароля отправлена на почту
        
        '422':
          description: Некорректный email
  
  /api/password/reset:
    post:
      summary: Сброс пароля пользователя
      tags:
        - Password
      operationId: ResetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetPassword"
      responses:
        '200':
          description: Пароль успешно сброшен
        '422':
          description: Некорректные данные
          
  /api/organizations/{limit}/{offset}:
    get:
      summary: Получение организаций
      operationId: GetAllOrganizations
      tags: 
        - Organizations
        
      parameters:
        - name: limit
          in: path
          required: true
          description: Количество пользователей
          schema:
            type: integer
            
        - name: offset
          in: path
          required: true
          description: Игнорирование пользователей
          schema:
            type: integer
            
      responses:
        '200':
          description: Успешный вывод всех организаций
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Organizations"
  
  /api/organizations/{id}:
    get:
      summary: Поиск организации по id
      tags: 
        - Organizations
      
      operationId: GetOrganizationbyId
      
      parameters:
        - name: id
          in: path
          required: true
          description: id организации
          schema:
            type: integer
            
      responses:
        '200':
          description: Получение организации
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
                
        '404':
          description: Организация не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
                
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorize"
    
    patch:
      summary: Изменение названия организации
      tags:
        - Organizations
      operationId: UpdateNameOrganization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organization"
      
      parameters:
        - name: id
          in: path
          required: true
          description: id организации
          schema:
            type: integer
            
      responses:
        '201':
          description: Название организации изменено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorize"
                
        '422':
          description: Некорректное название
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntity"
    
    delete:
      summary: Удаление организации по id
      tags: 
        - Organizations
      
      operationId: DeleteOrganizationbyId
      
      parameters:
        - name: id
          in: path
          required: true
          description: id организации
          schema:
            type: integer
            
      responses:
        '200':
          description: Организация удалена
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
                
        '404':
          description: Организация не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
                
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorize"               
                
  /api/organizations/{name}:
    get:
      summary: Поиск организации по названию
      operationId: GetOrganizationbyName
      tags: 
        - Organizations
      
      parameters:
        - name: name
          in: path
          required: true
          description: Название организации
          schema:
            type: string
            
      responses:
        '200':
          description: Получение организации
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
  
  /api/organizations:
    post:
      summary: Создание организации
      tags:
        - Organizations
      operationId: CreateOrganization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organization"
    
      responses:
        '201':
          description: Организация создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
        
        '403':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorize"
                
        '422':
          description: Некорректное название
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnprocessableEntity"
                
  
  
components: 
  schemas:
    User:
      type: object
      required:
        - name
        - email
        
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: denis
        email:
          type: string
          example: denis.le2001@mail.ru
        avatar:
          type: string
          example: public/avatars/zgskmYPxeL5CE0SF9d3AxNkOPjy2KW3lMyJqBENy.png
          
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
      example:
        - id: 1,
          name: denis
          email: denis123@mail.ru
          avatar: public/avatars/zgskmYPxeL5CE0SF9d3AxNkOPjy2KW3lMyJqBENy.png
          
        - id: 2
          name: sergey
          email: sergey123@gmail.com
          avatar: null
        
        - id: 3
          name: alina
          email: alina123@yandex.ru
          avatar: null
       
    Organization:
      type: object
      required:
        - id
        
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Nokia
       
    Organizations:
      type: array
      items:
        $ref: "#/components/schemas/Organization"
      example:
        - id: 1
          name: Nokia
        
        - id: 2
          name: Microsoft
      
    NotFound:    
      type: object
      
      properties:
        message: 
          type: string
          example: Не найдено
      
    UnprocessableEntity:
      type: object
      
      properties:
        message: 
          type: array
          items:
            type: array
            items:
              type: string
          example:
          - email: [The email must be a valid email address, The email must be at least 6 characters]
          - name: [The name field is required, The name must be at least 2 characters]
          - password: [The password must be at least 6 characters]
    
    AccessLogin:
      type: object
      
      properties:
        message:
          type: string
          example: Пользователь успешно авторизован
        id: 
          type: integer
          example: 7
        token:
          type: string
          example: 1|1gdsEDmjcD6n6FH9vMV7aVhDDtn8nGFJKk8qjQJI
        
    ResetPassword:
      type: object
      required:
            - email
            - token
            - password
            - confirm_password
      properties:
        email:
          type: string
          example: denisle@mail.ru
        token:
          type: string
          example: 86b7f816662e58966581091c52e92d5f88afd45bf268386a20c53eb92646a237
        password:
          type: string
          example: hard_pass
        confirm_password:
          type: string
          example: hard_pass
    
    Authorize:
      properties:
        message:
          type: string
          example: Пользователь не авторизован
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      